---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    apt: name=apache2 state=latest
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
